[0m09:54:41.658033 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x746d86c23e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x746d84e5c440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x746d84e5ec30>]}


============================== 09:54:41.663124 | 9eff52c7-39a9-4af3-a03f-be0eae6cbe8f ==============================
[0m09:54:41.663124 [info ] [MainThread]: Running with dbt=1.9.4
[0m09:54:41.663924 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/codespace/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init dataops_project', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:54:41.674868 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/home/codespace/.dbt')}
[0m09:54:41.675393 [info ] [MainThread]: Creating dbt configuration folder at 
[0m09:54:41.676783 [debug] [MainThread]: Starter project path: /usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/include/starter_project
[0m09:54:41.679403 [info ] [MainThread]: 
Your new dbt project "dataops_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:54:41.680130 [info ] [MainThread]: Setting up your profile.
[0m09:55:01.017252 [error] [MainThread]: Encountered an error:

[0m09:55:01.019594 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/click/termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m09:55:01.021581 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 19.415815, "process_in_blocks": "30112", "process_kernel_time": 0.156788, "process_mem_max_rss": "95740", "process_out_blocks": "64", "process_user_time": 1.442058}
[0m09:55:01.022231 [debug] [MainThread]: Command `dbt init` failed at 09:55:01.022115 after 19.42 seconds
[0m09:55:01.022852 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x746d84c72a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x746d847a9cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x746d8493fc80>]}
[0m09:55:01.023384 [debug] [MainThread]: Flushing usage events
[0m09:55:01.394476 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:55:30.282516 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7663a48840e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7663a26e5580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7663a2468a70>]}


============================== 09:55:30.285754 | 558aa794-2332-4fff-95ee-e6e0795351b3 ==============================
[0m09:55:30.285754 [info ] [MainThread]: Running with dbt=1.9.4
[0m09:55:30.286526 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/codespace/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init dataops_project', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:55:30.297512 [debug] [MainThread]: Starter project path: /usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/include/starter_project
[0m09:55:30.300059 [info ] [MainThread]: 
Your new dbt project "dataops_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:55:30.300672 [info ] [MainThread]: Setting up your profile.
[0m09:55:40.232453 [error] [MainThread]: Encountered an error:

[0m09:55:40.234868 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/click/termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m09:55:40.236248 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 10.003636, "process_in_blocks": "0", "process_kernel_time": 0.106736, "process_mem_max_rss": "95748", "process_out_blocks": "72", "process_user_time": 1.31076}
[0m09:55:40.236888 [debug] [MainThread]: Command `dbt init` failed at 09:55:40.236775 after 10.00 seconds
[0m09:55:40.237373 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7663a28ebef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7663a23a7200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7663a23edb50>]}
[0m09:55:40.238084 [debug] [MainThread]: Flushing usage events
[0m09:55:40.557892 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:57:08.154268 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e50996c890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e508ff3c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e509308440>]}


============================== 09:57:08.157643 | 2ba4255e-9a54-4047-a6fd-f78591455008 ==============================
[0m09:57:08.157643 [info ] [MainThread]: Running with dbt=1.9.4
[0m09:57:08.158443 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/codespace/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init dataops_project', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:57:08.170128 [debug] [MainThread]: Starter project path: /usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/include/starter_project
[0m09:57:08.172781 [info ] [MainThread]: 
Your new dbt project "dataops_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:57:08.173462 [info ] [MainThread]: Setting up your profile.
[0m10:00:03.980636 [info ] [MainThread]: Profile dataops_project written to /home/codespace/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m10:00:03.982420 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 175.87811, "process_in_blocks": "0", "process_kernel_time": 0.104618, "process_mem_max_rss": "99216", "process_out_blocks": "80", "process_user_time": 1.366501}
[0m10:00:03.983134 [debug] [MainThread]: Command `dbt init` succeeded at 10:00:03.983013 after 175.88 seconds
[0m10:00:03.983598 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e508ff3c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e508fbc980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78e508def470>]}
[0m10:00:03.984130 [debug] [MainThread]: Flushing usage events
[0m10:00:04.315083 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:00:44.673201 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1d1fb818e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1d1ffe4e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1d203686e0>]}


============================== 10:00:44.676459 | 075b6530-be8f-4760-af55-7e21fea4fe36 ==============================
[0m10:00:44.676459 [info ] [MainThread]: Running with dbt=1.9.4
[0m10:00:44.677267 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/codespace/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dataops_project', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:00:44.688391 [debug] [MainThread]: Starter project path: /usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/include/starter_project
[0m10:00:44.691045 [info ] [MainThread]: 
Your new dbt project "dataops_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:00:44.691759 [info ] [MainThread]: Setting up your profile.
[0m10:02:31.028695 [info ] [MainThread]: Profile dataops_project written to /home/codespace/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m10:02:31.030267 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 106.40816, "process_in_blocks": "0", "process_kernel_time": 0.131402, "process_mem_max_rss": "99448", "process_out_blocks": "88", "process_user_time": 1.316018}
[0m10:02:31.030952 [debug] [MainThread]: Command `dbt init` succeeded at 10:02:31.030829 after 106.41 seconds
[0m10:02:31.031427 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1d1f961250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1d20142480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1d20142c90>]}
[0m10:02:31.032076 [debug] [MainThread]: Flushing usage events
[0m10:02:31.382671 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:46:55.104234 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7168bb1003b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7168b918b530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7168babba270>]}


============================== 10:46:55.108017 | ceeb74fb-a764-4130-9738-88fd3170fa2a ==============================
[0m10:46:55.108017 [info ] [MainThread]: Running with dbt=1.9.4
[0m10:46:55.108822 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/workspaces/Atelier-DataOps/dataops_yasmine-main', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:46:55.120008 [info ] [MainThread]: dbt version: 1.9.4
[0m10:46:55.120551 [info ] [MainThread]: python version: 3.12.1
[0m10:46:55.121153 [info ] [MainThread]: python path: /usr/local/python/3.12.1/bin/python3
[0m10:46:55.121605 [info ] [MainThread]: os info: Linux-6.8.0-1027-azure-x86_64-with-glibc2.31
[0m10:46:55.122081 [info ] [MainThread]: Using profiles dir at /workspaces/Atelier-DataOps/dataops_yasmine-main
[0m10:46:55.122506 [info ] [MainThread]: Using profiles.yml file at /workspaces/Atelier-DataOps/dataops_yasmine-main/profiles.yml
[0m10:46:55.122950 [info ] [MainThread]: Using dbt_project.yml file at /workspaces/Atelier-DataOps/dataops_yasmine-main/dbt_project.yml
[0m10:46:55.123389 [info ] [MainThread]: Configuration:
[0m10:46:55.123828 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m10:46:55.124249 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m10:46:55.124659 [info ] [MainThread]: Required dependencies:
[0m10:46:55.125180 [debug] [MainThread]: Executing "git --help"
[0m10:46:55.127809 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m10:46:55.128632 [debug] [MainThread]: STDERR: "b''"
[0m10:46:55.129192 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m10:46:55.129668 [info ] [MainThread]: Connection test skipped since no profile was found
[0m10:46:55.130227 [info ] [MainThread]: [31m2 checks failed:[0m
[0m10:46:55.130694 [info ] [MainThread]: dbt looked for a profiles.yml file in /workspaces/Atelier-DataOps/dataops_yasmine-main/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m10:46:55.131175 [info ] [MainThread]: Project loading failed for the following reason:
 project path </workspaces/Atelier-DataOps/dataops_yasmine-main/dbt_project.yml> not found

[0m10:46:55.132160 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.07842781, "process_in_blocks": "8", "process_kernel_time": 0.107511, "process_mem_max_rss": "95892", "process_out_blocks": "24", "process_user_time": 1.334938}
[0m10:46:55.132804 [debug] [MainThread]: Command `dbt debug` failed at 10:46:55.132673 after 0.08 seconds
[0m10:46:55.133270 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7168bb1003b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7168b8c84290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7168b8c0ff50>]}
[0m10:46:55.133799 [debug] [MainThread]: Flushing usage events
[0m10:46:55.497336 [debug] [MainThread]: An error was encountered while trying to flush usage events
